export const categories = [
    'gas_transport', 'grocery_pos', 'home', 'shopping_pos', 'kids_pets',
    'shopping_net', 'entertainment', 'food_dining', 'personal_care',
    'health_fitness', 'misc_pos', 'misc_net', 'grocery_net', 'travel'
  ];
  
  export const genders = ['F', 'M'];
  
  export const states = [
    'TX', 'NY', 'PA', 'CA', 'OH', 'MI', 'IL', 'FL', 'AL', 'MO', 'MN', 'AR',
    'NC', 'WI', 'VA', 'SC', 'KY', 'IN', 'IA', 'OK', 'MD', 'GA', 'WV', 'NJ',
    'NE', 'KS', 'MS', 'LA', 'WY', 'WA', 'OR', 'TN', 'ME', 'NM', 'ND', 'CO',
    'MA', 'SD', 'VT', 'MT', 'AZ', 'UT', 'NH', 'CT', 'NV', 'ID', 'DC', 'HI',
    'AK', 'RI', 'DE'
  ];
  
  export const jobs = [
    'Film/video editor', 'Exhibition designer', 'Naval architect', 'Surveyor, land/geomatics',
    'Materials engineer', 'Designer, ceramics/pottery', 'Systems developer', 'IT trainer',
    'Financial adviser', 'Environmental consultant', 'Chartered public finance accountant',
    'Scientist, audiological', 'Chief Executive Officer', 'Copywriter, advertising', 'Comptroller',
    'Sub', 'Podiatrist', 'Agricultural consultant', 'Paramedic', 'Magazine features editor',
    'Historic buildings inspector/conservation officer', 'Building surveyor', 'Musician', 'Librarian, public','Scientist, research (maths)',
'Mining engineer',
'Audiological scientist',
'Water engineer',
'Barrister',
'Immunologist',
'Clothing/textile technologist',
'Prison officer',
'Financial trader',
'Energy engineer',
'Quantity surveyor',
'Claims inspector/assessor',
'Petroleum engineer',
'Mechanical engineer',
'Make',
'Engineer, automotive',
'Geoscientist',
'Secondary school teacher',
'Land/geomatics surveyor',
'Counsellor',
'Firefighter',
'Early years teacher',
'Sales professional, IT',
'Pensions consultant',
'Psychologist, forensic',
'Psychotherapist, child',
'Librarian, academic',
'Electrical engineer',
'Research scientist (physical sciences)',
'Insurance underwriter',
'Science writer',
'Drilling engineer',
'Television production assistant',
'Medical sales representative',
'Chartered loss adjuster',
'Trade mark attorney',
'Engineer, biomedical',
'Scientist, marine',
'Special educational needs teacher',
'Chemical engineer',
'Cytogeneticist',
'Multimedia programmer',
'Accounting technician',
'Trading standards officer',
'Dealer',
'Counselling psychologist',
'Engineer, production',
'Technical brewer',
'Toxicologist',
'Social researcher',
'Race relations officer',
'Radio producer',
'Teacher, special educational needs',
'Fine artist',
'Physiotherapist',
'Engineer, control and instrumentation',
'Chief Strategy Officer',
'Radio broadcast assistant',
'Therapist, occupational',
'Surveyor, minerals',
'Educational psychologist',
'Ceramics designer',
'Advertising account planner',
'Scientist, biomedical',
'Television/film/video producer',
'Futures trader',
'Exhibitions officer, museum/gallery',
'Programme researcher, broadcasting/film/video',
'Town planner',
'Further education lecturer',
'Surgeon',
'Senior tax professional/tax inspector',
'Designer, industrial/product',
'Buyer, industrial',
'Probation officer',
'Applications developer',
'Curator',
'English as a second language teacher',
'Lexicographer',
'Engineering geologist',
'Child psychotherapist',
'Occupational psychologist',
'Pilot, airline',
'Development worker, community',
'Herbalist',
'Radiographer, therapeutic',
'Press photographer',
'Archaeologist',
'Public relations account executive',
'Facilities manager',
'Forensic psychologist',
'Fisheries officer',
'Research officer, political party',
'Engineer, electronics',
'Editor, commissioning',
'Broadcast presenter',
'Systems analyst',
'Exercise physiologist',
'Dispensing optician',
'Engineer, mining',
'Insurance risk surveyor',
'Retail merchandiser',
'Administrator',
'Chiropodist',
'Operations geologist',
'Lecturer, further education',
'Hospital doctor',
'Private music teacher',
'Physicist, medical',
'Learning disability nurse',
'Call centre manager',
'Travel agency manager',
'Research officer, trade union',
'Heritage manager',
'Insurance broker',
'Structural engineer',
'Psychologist, counselling',
'Colour technologist',
'Amenity horticulturist',
'Tree surgeon',
'Television floor manager',
'Geologist, engineering',
'Producer, radio',
'Metallurgist',
'Education officer, museum',
'Phytotherapist',
'Arboriculturist',
'Journalist, newspaper',
'Occupational hygienist',
'Regulatory affairs officer',
'Video editor',
'Biomedical scientist',
'Site engineer',
'Electronics engineer',
'Leisure centre manager',
'Tourist information centre manager',
'Designer, jewellery',
'Development worker, international aid',
"Barrister's clerk",
'Production manager',
'Licensed conveyancer',
'Commercial horticulturist',
'Press sub',
'Warden/ranger',
'Manufacturing engineer',
'Designer, furniture',
'Radiographer, diagnostic',
'Music tutor',
'Chief Operating Officer',
'Tax inspector',
'Camera operator',
'Product/process development scientist',
'Health physicist',
'Engineer, land',
'Designer, exhibition/display',
'Freight forwarder',
'Contractor',
'Gaffer',
'Lecturer, higher education',
'Commercial/residential surveyor',
'Careers information officer',
'Energy manager',
"Nurse, children's",
'Administrator, local government',
'Wellsite geologist',
'Risk analyst',
'Market researcher',
'Chief Technology Officer',
'Soil scientist',
'Osteopath',
'Statistician',
'Health and safety adviser',
'Equality and diversity officer',
'Programmer, multimedia',
'Doctor, general practice',
'Human resources officer',
'Advice worker',
'Bookseller',
'Accountant, chartered public finance',
'Police officer',
'Fitness centre manager',
'Tourism officer',
'Administrator, education',
'Building control surveyor',
'Mental health nurse',
'Maintenance engineer',
'Operational researcher',
'Music therapist',
'Web designer',
'Community arts worker',
'Engineer, petroleum',
'Health service manager',
'Chief Financial Officer',
'Database administrator',
'Land',
'Optician, dispensing',
'Doctor, hospital',
'Therapist, sports',
'Therapist, art',
'Armed forces training and education officer',
'Paediatric nurse',
'Media buyer',
'Geochemist',
'Teacher, secondary school',
'Product designer',
'Waste management officer',
'Patent attorney',
'Tax adviser',
'Therapist, horticultural',
'Investment analyst',
'Administrator, charities/voluntary organisations',
'Surveyor, rural practice',
'Teacher, early years/pre',
'Intelligence analyst',
'Transport planner',
'Horticultural therapist',
'Neurosurgeon',
'Sports development officer',
'Chief Marketing Officer',
'Retail buyer',
'Charity fundraiser',
'Scientist, physiological',
'Psychologist, sport and exercise',
'Museum/gallery conservator',
'Animal nutritionist',
'Airline pilot',
'Glass blower/designer',
"Politician's assistant",
'Industrial/product designer',
'Landscape architect',
'Pension scheme manager',
'Seismic interpreter',
'Telecommunications researcher',
'Clinical biochemist',
'Psychiatrist',
'Editor, film/video',
'Geologist, wellsite',
'Sport and exercise psychologist',
'Nutritional therapist',
'Clinical research associate',
'Museum/gallery exhibitions officer',
'Secretary/administrator',
'Communications engineer',
'Therapist, drama',
'Furniture designer',
'Immigration officer',
'Architect',
'Editor, magazine features',
'Art therapist',
'Psychotherapist',
'Scientist, research (physical sciences)',
'Medical secretary',
'Cartographer',
'Farm manager',
'Investment banker, corporate',
'Scientific laboratory technician',
'Retail banker',
'Public house manager',
'Public affairs consultant',
'Animal technologist',
'Engineer, drilling',
'Community education officer',
'Biomedical engineer',
'Research scientist (life sciences)',
'Information systems manager',
'Health promotion specialist',
'Horticulturist, commercial',
'Pharmacist, community',
'Volunteer coordinator',
'Arts development officer',
'Civil engineer, contracting',
'Corporate investment banker',
'Herpetologist',
'Aid worker',
'General practice doctor',
'Dance movement psychotherapist',
'Engineer, technical sales',
'Theme park manager',
'Health visitor',
'Animator',
'Acupuncturist',
'Advertising account executive',
'Medical physicist',
'Engineer, agricultural',
'Embryologist, clinical',
'Designer, interior/spatial',
'Pharmacologist',
'Oceanographer',
'Network engineer',
'Special effects artist',
'Sales executive',
'Barista',
'Event organiser',
'Psychologist, clinical',
'Theatre director',
'Planning and development surveyor',
'Community pharmacist',
'Surveyor, mining',
'Learning mentor',
'Orthoptist',
'Training and development officer',
'Field seismologist',
'Set designer',
'Emergency planning/management officer',
'Theatre manager',
'Equities trader',
'Logistics and distribution manager',
'Environmental health practitioner',
'Research scientist (maths)',
'Psychiatric nurse',
'Therapist, music',
'Diagnostic radiographer',
'Interpreter',
'Optometrist',
'Engineer, communications',
'Aeronautical engineer',
'Production engineer',
'Building services engineer',
'Garment/textile technologist',
'Mudlogger',
'Hydrologist',
'Physiological scientist',
'Management consultant',
'Social research officer, government',
'Engineer, maintenance',
'Armed forces logistics/support/administrative officer',
'Public librarian',
'Higher education careers adviser',
'Rural practice surveyor',
'Records manager',
'Geophysicist/field seismologist',
'Control and instrumentation engineer',
'Commissioning editor',
'Chartered accountant',
'Archivist',
'Quarry manager',
'Teaching laboratory technician',
'Location manager',
'Engineer, civil (contracting)',
'Illustrator',
'Conservation officer, historic buildings',
'Teacher, primary school',
'Medical technical officer',
'Pharmacist, hospital',
'Media planner',
'Plant breeder/geneticist',
'Designer, multimedia',
'Economist',
'Sports administrator',
'Ambulance person',
'Museum education officer',
'Biochemist, clinical',
'Presenter, broadcasting',
'Designer, textile',
'Scientist, clinical (histocompatibility and immunogenetics)',
'Hydrographic surveyor',
'Academic librarian',
'Pathologist',
'Hospital pharmacist',
'Environmental education officer',
'Chief of Staff',
'Furniture conservator/restorer',
'Company secretary',
'Engineer, broadcasting (operations)',
'Air broker',
'Engineer, building services',
'Retail manager',
'Engineer, aeronautical',
'Stage manager',
'Production assistant, radio',
'Advertising copywriter',
'Education administrator',
'Art gallery manager',
'Cabin crew',
'Insurance claims handler',
'Civil Service fast streamer',
'Chartered legal executive (England and Wales)',
'Outdoor activities/education manager',
'Ecologist',
'Jewellery designer',
'Loss adjuster, chartered',
'Architectural technologist',
'Nurse, mental health',
'Teacher, English as a foreign language',
'Programmer, applications',
'Research scientist (medical)',
'Chemist, analytical',
'Product manager',
'Manufacturing systems engineer',
'Clinical psychologist',
'IT consultant',
'Scientist, research (medical)',
'Visual merchandiser',
'Lawyer',
'Geneticist, molecular',
'Community development worker',
'TEFL teacher',
'Engineer, civil (consulting)',
'Magazine journalist',
'Engineer, manufacturing',
'Estate manager/land agent',
'Merchandiser, retail',
'Accountant, chartered certified',
'Administrator, arts',
'Minerals surveyor',
'Horticultural consultant',
'Production assistant, television',
'Conservator, furniture',
'Associate Professor',
'Oncologist',
'Restaurant manager, fast food',
'Designer, television/film set',
'Surveyor, hydrographic',
'Catering manager',
'Charity officer',
'Solicitor, Scotland',
'Field trials officer',
'Artist',
'Conservator, museum/gallery',
'Occupational therapist',
'Air cabin crew',
'Broadcast engineer',
'Textile designer',
'Local government officer',
'Clinical cytogeneticist',
'Data scientist',
'Engineer, materials',
'Teacher, adult education',
'Hotel manager',
'Environmental manager',
'Public relations officer',
'Primary school teacher',
'Education officer, community',
'Interior and spatial designer',
'Nature conservation officer',
'Writer',
'Television camera operator',
'Marketing executive',
'Civil Service administrator',
'Water quality scientist',
'Purchasing manager',
'Professor Emeritus',
'Copy',
'Investment banker, operational',
'Analytical chemist',
'English as a foreign language teacher',
'Engineer, structural',
'Producer, television/film/video',
'Tour manager',
'Buyer, retail',
'Hydrogeologist',
'Dancer',
'Air traffic controller',
'Careers adviser',
'Sales promotion account executive',
'Personnel officer',
'Engineer, site',
'Legal secretary',
'Accountant, chartered',
'Homeopath',
'Solicitor',
'Industrial buyer',
'Broadcast journalist',
'Forest/woodland manager',
'Veterinary surgeon',
'Armed forces technical officer',
'Information officer',
'Contracting civil engineer',
'Ship broker',
'Warehouse manager'];